{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "dried-louisville",
   "metadata": {
    "id": "dried-louisville"
   },
   "source": [
    "### Setup libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ortbQg9AP2m4",
   "metadata": {
    "id": "ortbQg9AP2m4"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting deeppavlov\n",
      "  Using cached deeppavlov-0.15.0-py3-none-any.whl (907 kB)\n",
      "Requirement already satisfied: scipy==1.4.1 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from deeppavlov) (1.4.1)\n",
      "Collecting overrides==2.7.0\n",
      "  Using cached overrides-2.7.0-py3-none-any.whl\n",
      "Requirement already satisfied: filelock==3.0.12 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (3.0.12)\n",
      "Requirement already satisfied: click==7.1.2 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (7.1.2)\n",
      "Requirement already satisfied: uvicorn==0.11.7 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (0.11.7)\n",
      "Collecting pymorphy2==0.8\n",
      "  Using cached pymorphy2-0.8-py2.py3-none-any.whl (46 kB)\n",
      "Collecting ruamel.yaml==0.15.100\n",
      "  Using cached ruamel.yaml-0.15.100-py3-none-any.whl\n",
      "Collecting sacremoses==0.0.35\n",
      "  Using cached sacremoses-0.0.35-py3-none-any.whl\n",
      "Requirement already satisfied: pydantic==1.3 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (1.3)\n",
      "Collecting pandas==0.25.3\n",
      "  Using cached pandas-0.25.3-cp38-cp38-win_amd64.whl (9.4 MB)\n",
      "Requirement already satisfied: tqdm==4.41.1 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from deeppavlov) (4.41.1)\n",
      "Collecting prometheus-client==0.7.1\n",
      "  Using cached prometheus_client-0.7.1-py3-none-any.whl\n",
      "Requirement already satisfied: requests==2.22.0 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (2.22.0)\n",
      "Collecting nltk==3.4.5\n",
      "  Using cached nltk-3.4.5-py3-none-any.whl\n",
      "Collecting scikit-learn==0.21.2\n",
      "  Using cached scikit-learn-0.21.2.tar.gz (12.2 MB)\n",
      "Collecting aio-pika==6.4.1\n",
      "  Using cached aio_pika-6.4.1-py3-none-any.whl (40 kB)\n",
      "Requirement already satisfied: pytz==2019.1 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (2019.1)\n",
      "Collecting rusenttokenize==0.0.5\n",
      "  Using cached rusenttokenize-0.0.5-py3-none-any.whl (10 kB)\n",
      "Requirement already satisfied: pymorphy2-dicts-ru in c:\\users\\admin\\anaconda3\\lib\\site-packages (from deeppavlov) (2.4.417127.4579844)\n",
      "Requirement already satisfied: numpy==1.18.0 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from deeppavlov) (1.18.0)\n",
      "Collecting uvloop==0.14.0\n",
      "  Using cached uvloop-0.14.0.tar.gz (2.0 MB)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Admin\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\uvloop_74280bdf07ae447c9b0080de5ff66110\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\uvloop_74280bdf07ae447c9b0080de5ff66110\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-pip-egg-info-93pkf708'\n",
      "         cwd: C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\uvloop_74280bdf07ae447c9b0080de5ff66110\\\n",
      "    Complete output (5 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\uvloop_74280bdf07ae447c9b0080de5ff66110\\setup.py\", line 15, in <module>\n",
      "        raise RuntimeError('uvloop does not support Windows at the moment')\n",
      "    RuntimeError: uvloop does not support Windows at the moment\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.tar.gz#sha256=123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e (from https://pypi.org/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\Admin\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-wheel-_bfqegg3'\n",
      "       cwd: C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\\n",
      "  Complete output (121 lines):\n",
      "  Partial import of sklearn during the build process.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting deeppavlov\n",
      "  Using cached deeppavlov-0.14.1-py3-none-any.whl (988 kB)\n",
      "  Using cached deeppavlov-0.14.0-py3-none-any.whl (988 kB)\n",
      "Collecting pytelegrambotapi==3.6.7\n",
      "  Using cached pyTelegramBotAPI-3.6.7-py3-none-any.whl\n",
      "Requirement already satisfied: Cython==0.29.14 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from deeppavlov) (0.29.14)\n",
      "Collecting fastapi==0.47.1\n",
      "  Using cached fastapi-0.47.1-py3-none-any.whl (43 kB)\n",
      "Collecting pyopenssl==19.1.0\n",
      "  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)\n",
      "Collecting h5py==2.10.0\n",
      "  Using cached h5py-2.10.0-cp38-cp38-win_amd64.whl (2.5 MB)\n",
      "Requirement already satisfied: yarl in c:\\users\\admin\\anaconda3\\lib\\site-packages (from aio-pika==6.4.1->deeppavlov) (1.6.3)\n",
      "Requirement already satisfied: aiormq<4,>=3.2.0 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from aio-pika==6.4.1->deeppavlov) (3.3.1)\n",
      "Requirement already satisfied: starlette<=0.12.9,>=0.12.9 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from fastapi==0.47.1->deeppavlov) (0.12.9)\n",
      "Requirement already satisfied: six in c:\\users\\admin\\anaconda3\\lib\\site-packages (from h5py==2.10.0->deeppavlov) (1.15.0)\n",
      "Requirement already satisfied: python-dateutil>=2.6.1 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from pandas==0.25.3->deeppavlov) (2.8.1)\n",
      "Requirement already satisfied: dawg-python>=0.7 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from pymorphy2==0.8->deeppavlov) (0.7.2)\n",
      "Requirement already satisfied: pymorphy2-dicts<3.0,>=2.4 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from pymorphy2==0.8->deeppavlov) (2.4.393442.3710985)\n",
      "Requirement already satisfied: docopt>=0.6 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from pymorphy2==0.8->deeppavlov) (0.6.2)\n",
      "Requirement already satisfied: cryptography>=2.8 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from pyopenssl==19.1.0->deeppavlov) (3.4.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from requests==2.22.0->deeppavlov) (2020.12.5)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from requests==2.22.0->deeppavlov) (1.25.11)\n",
      "Requirement already satisfied: idna<2.9,>=2.5 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from requests==2.22.0->deeppavlov) (2.8)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from requests==2.22.0->deeppavlov) (3.0.4)\n",
      "Requirement already satisfied: joblib in c:\\users\\admin\\anaconda3\\lib\\site-packages (from sacremoses==0.0.35->deeppavlov) (1.0.1)\n",
      "Requirement already satisfied: h11<0.10,>=0.8 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from uvicorn==0.11.7->deeppavlov) (0.9.0)\n",
      "Requirement already satisfied: websockets==8.* in c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages (from uvicorn==0.11.7->deeppavlov) (8.1)\n",
      "Requirement already satisfied: pamqp==2.3.0 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from aiormq<4,>=3.2.0->aio-pika==6.4.1->deeppavlov) (2.3.0)\n",
      "Requirement already satisfied: cffi>=1.12 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from cryptography>=2.8->pyopenssl==19.1.0->deeppavlov) (1.14.5)\n",
      "Requirement already satisfied: pycparser in c:\\users\\admin\\anaconda3\\lib\\site-packages (from cffi>=1.12->cryptography>=2.8->pyopenssl==19.1.0->deeppavlov) (2.20)\n",
      "Requirement already satisfied: multidict>=4.0 in c:\\users\\admin\\anaconda3\\lib\\site-packages (from yarl->aio-pika==6.4.1->deeppavlov) (5.1.0)\n",
      "Building wheels for collected packages: scikit-learn\n",
      "  Building wheel for scikit-learn (setup.py): started\n",
      "  Building wheel for scikit-learn (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for scikit-learn\n",
      "Failed to build scikit-learn\n",
      "Installing collected packages: scikit-learn, sacremoses, rusenttokenize, ruamel.yaml, pytelegrambotapi, pyopenssl, pymorphy2, prometheus-client, pandas, overrides, nltk, h5py, fastapi, aio-pika, deeppavlov\n",
      "  Attempting uninstall: scikit-learn\n",
      "    Found existing installation: scikit-learn 0.23.2\n",
      "    Uninstalling scikit-learn-0.23.2:\n",
      "      Successfully uninstalled scikit-learn-0.23.2\n",
      "    Running setup.py install for scikit-learn: started\n",
      "    Running setup.py install for scikit-learn: finished with status 'error'\n",
      "  Rolling back uninstall of scikit-learn\n",
      "  Moving to c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages\\scikit_learn-0.23.2.dist-info\\\n",
      "   from C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\~cikit_learn-0.23.2.dist-info\n",
      "  Moving to c:\\users\\admin\\appdata\\roaming\\python\\python38\\site-packages\\sklearn\\\n",
      "   from C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\~klearn\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  blas_opt_info:\n",
      "  blas_mkl_info:\n",
      "  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "  customize MSVCCompiler\n",
      "    libraries mkl_rt not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  blis_info:\n",
      "    libraries blis not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  openblas_info:\n",
      "    libraries openblas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "  customize GnuFCompiler\n",
      "  Could not locate executable g77\n",
      "  Could not locate executable f77\n",
      "  customize IntelVisualFCompiler\n",
      "  Could not locate executable ifort\n",
      "  Could not locate executable ifl\n",
      "  customize AbsoftFCompiler\n",
      "  Could not locate executable f90\n",
      "  customize CompaqVisualFCompiler\n",
      "  Could not locate executable DF\n",
      "  customize IntelItaniumVisualFCompiler\n",
      "  Could not locate executable efl\n",
      "  customize Gnu95FCompiler\n",
      "  Could not locate executable gfortran\n",
      "  Could not locate executable f95\n",
      "  customize G95FCompiler\n",
      "  Could not locate executable g95\n",
      "  customize IntelEM64VisualFCompiler\n",
      "  customize IntelEM64TFCompiler\n",
      "  Could not locate executable efort\n",
      "  Could not locate executable efc\n",
      "  customize PGroupFlangCompiler\n",
      "  Could not locate executable flang\n",
      "  don't know how to compile Fortran code on platform 'nt'\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_blas_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries tatlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_3_10_blas_info:\n",
      "    libraries satlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_blas_threads_info:\n",
      "  Setting PTATLAS=ATLAS\n",
      "    libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  atlas_blas_info:\n",
      "    libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  accelerate_info:\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "      Optimized (vendor) Blas libraries are not found.\n",
      "      Falls back to netlib Blas library which has worse performance.\n",
      "      A better performance should be easily gained by switching\n",
      "      Blas library.\n",
      "    if self._calc_info(blas):\n",
      "  blas_info:\n",
      "    libraries blas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "      Blas (http://www.netlib.org/blas/) libraries not found.\n",
      "      Directories to search for the libraries can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [blas]) or by setting\n",
      "      the BLAS environment variable.\n",
      "    if self._calc_info(blas):\n",
      "  blas_src_info:\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "      Blas (http://www.netlib.org/blas/) sources not found.\n",
      "      Directories to search for the sources can be specified in the\n",
      "      numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
      "      the BLAS_SRC environment variable.\n",
      "    if self._calc_info(blas):\n",
      "    NOT AVAILABLE\n",
      "  \n",
      "  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 290, in <module>\n",
      "      setup_package()\n",
      "    File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 286, in setup_package\n",
      "      setup(**metadata)\n",
      "    File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\core.py\", line 137, in setup\n",
      "      config = configuration()\n",
      "    File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 174, in configuration\n",
      "      config.add_subpackage('sklearn')\n",
      "    File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 1033, in add_subpackage\n",
      "      config_list = self.get_subpackage(subpackage_name, subpackage_path,\n",
      "    File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 999, in get_subpackage\n",
      "      config = self._get_configuration_from_setup_py(\n",
      "    File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 941, in _get_configuration_from_setup_py\n",
      "      config = setup_module.configuration(*args)\n",
      "    File \"sklearn\\setup.py\", line 80, in configuration\n",
      "      maybe_cythonize_extensions(top_path, config)\n",
      "    File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\sklearn\\_build_utils\\__init__.py\", line 68, in maybe_cythonize_extensions\n",
      "      with_openmp = check_openmp_support()\n",
      "    File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\sklearn\\_build_utils\\openmp_helpers.py\", line 83, in check_openmp_support\n",
      "      ccompiler.compile(['test_openmp.c'], output_dir='objects',\n",
      "    File \"C:\\Users\\Admin\\anaconda3\\lib\\distutils\\_msvccompiler.py\", line 327, in compile\n",
      "      self.initialize()\n",
      "    File \"C:\\Users\\Admin\\anaconda3\\lib\\distutils\\_msvccompiler.py\", line 224, in initialize\n",
      "      vc_env = _get_vc_env(plat_spec)\n",
      "    File \"C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\setuptools\\msvc.py\", line 314, in msvc14_get_vc_env\n",
      "      return _msvc14_get_vc_env(plat_spec)\n",
      "    File \"C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\setuptools\\msvc.py\", line 268, in _msvc14_get_vc_env\n",
      "      raise distutils.errors.DistutilsPlatformError(\n",
      "  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with \"Build Tools for Visual Studio\": https://visualstudio.microsoft.com/downloads/\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for scikit-learn\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Admin\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-record-3op_il9q\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\Admin\\anaconda3\\Include\\scikit-learn'\n",
      "         cwd: C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\\n",
      "    Complete output (121 lines):\n",
      "    Partial import of sklearn during the build process.\n",
      "    blas_opt_info:\n",
      "    blas_mkl_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries mkl_rt not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    blis_info:\n",
      "      libraries blis not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    openblas_info:\n",
      "      libraries openblas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "    customize GnuFCompiler\n",
      "    Could not locate executable g77\n",
      "    Could not locate executable f77\n",
      "    customize IntelVisualFCompiler\n",
      "    Could not locate executable ifort\n",
      "    Could not locate executable ifl\n",
      "    customize AbsoftFCompiler\n",
      "    Could not locate executable f90\n",
      "    customize CompaqVisualFCompiler\n",
      "    Could not locate executable DF\n",
      "    customize IntelItaniumVisualFCompiler\n",
      "    Could not locate executable efl\n",
      "    customize Gnu95FCompiler\n",
      "    Could not locate executable gfortran\n",
      "    Could not locate executable f95\n",
      "    customize G95FCompiler\n",
      "    Could not locate executable g95\n",
      "    customize IntelEM64VisualFCompiler\n",
      "    customize IntelEM64TFCompiler\n",
      "    Could not locate executable efort\n",
      "    Could not locate executable efc\n",
      "    customize PGroupFlangCompiler\n",
      "    Could not locate executable flang\n",
      "    don't know how to compile Fortran code on platform 'nt'\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_3_10_blas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "      libraries tatlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_3_10_blas_info:\n",
      "      libraries satlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_blas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "      libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    atlas_blas_info:\n",
      "      libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    accelerate_info:\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "        Optimized (vendor) Blas libraries are not found.\n",
      "        Falls back to netlib Blas library which has worse performance.\n",
      "        A better performance should be easily gained by switching\n",
      "        Blas library.\n",
      "      if self._calc_info(blas):\n",
      "    blas_info:\n",
      "      libraries blas not found in ['C:\\\\Users\\\\Admin\\\\anaconda3\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Admin\\\\anaconda3\\\\libs']\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "        Blas (http://www.netlib.org/blas/) libraries not found.\n",
      "        Directories to search for the libraries can be specified in the\n",
      "        numpy/distutils/site.cfg file (section [blas]) or by setting\n",
      "        the BLAS environment variable.\n",
      "      if self._calc_info(blas):\n",
      "    blas_src_info:\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\system_info.py:1896: UserWarning:\n",
      "        Blas (http://www.netlib.org/blas/) sources not found.\n",
      "        Directories to search for the sources can be specified in the\n",
      "        numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
      "        the BLAS_SRC environment variable.\n",
      "      if self._calc_info(blas):\n",
      "      NOT AVAILABLE\n",
      "    \n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 290, in <module>\n",
      "        setup_package()\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 286, in setup_package\n",
      "        setup(**metadata)\n",
      "      File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\core.py\", line 137, in setup\n",
      "        config = configuration()\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\setup.py\", line 174, in configuration\n",
      "        config.add_subpackage('sklearn')\n",
      "      File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 1033, in add_subpackage\n",
      "        config_list = self.get_subpackage(subpackage_name, subpackage_path,\n",
      "      File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 999, in get_subpackage\n",
      "        config = self._get_configuration_from_setup_py(\n",
      "      File \"C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\distutils\\misc_util.py\", line 941, in _get_configuration_from_setup_py\n",
      "        config = setup_module.configuration(*args)\n",
      "      File \"sklearn\\setup.py\", line 80, in configuration\n",
      "        maybe_cythonize_extensions(top_path, config)\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\sklearn\\_build_utils\\__init__.py\", line 68, in maybe_cythonize_extensions\n",
      "        with_openmp = check_openmp_support()\n",
      "      File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-jzjrynrp\\scikit-learn_0aabea42199643f69645e909da747bb7\\sklearn\\_build_utils\\openmp_helpers.py\", line 83, in check_openmp_support\n",
      "        ccompiler.compile(['test_openmp.c'], output_dir='objects',\n",
      "      File \"C:\\Users\\Admin\\anaconda3\\lib\\distutils\\_msvccompiler.py\", line 327, in compile\n",
      "        self.initialize()\n",
      "      File \"C:\\Users\\Admin\\anaconda3\\lib\\distutils\\_msvccompiler.py\", line 224, in initialize\n",
      "        vc_env = _get_vc_env(plat_spec)\n",
      "      File \"C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\setuptools\\msvc.py\", line 314, in msvc14_get_vc_env\n",
      "        return _msvc14_get_vc_env(plat_spec)\n",
      "      File \"C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\setuptools\\msvc.py\", line 268, in _msvc14_get_vc_env\n",
      "        raise distutils.errors.DistutilsPlatformError(\n",
      "    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with \"Build Tools for Visual Studio\": https://visualstudio.microsoft.com/downloads/\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\Users\\Admin\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\Temp\\\\pip-install-jzjrynrp\\\\scikit-learn_0aabea42199643f69645e909da747bb7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-record-3op_il9q\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\Admin\\anaconda3\\Include\\scikit-learn' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "!pip install deeppavlov"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "unsigned-court",
   "metadata": {
    "id": "unsigned-court"
   },
   "source": [
    "### Import libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "phantom-guatemala",
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 17
    },
    "executionInfo": {
     "elapsed": 1089,
     "status": "ok",
     "timestamp": 1622017926369,
     "user": {
      "displayName": "Alexey Tankov",
      "photoUrl": "",
      "userId": "01729535101672247421"
     },
     "user_tz": -180
    },
    "id": "phantom-guatemala",
    "outputId": "1c792b0c-764a-4c4f-f459-e47ac195ee4d"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>.container { width:72.5% !important; }</style>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.core.display import display, HTML\n",
    "display(HTML(\"<style>.container { width:72.5% !important; }</style>\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cordless-colorado",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'deeppavlov'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-fb2f25801da6>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mdeeppavlov\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mbuild_model\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mconfigs\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'deeppavlov'"
     ]
    }
   ],
   "source": [
    "from deeppavlov import build_model, configs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "JW9sCUUGKfdQ",
   "metadata": {
    "id": "JW9sCUUGKfdQ"
   },
   "outputs": [],
   "source": [
    "# # Training (if you have your own data)\n",
    "# from deeppavlov import configs, train_evaluate_model_from_config\n",
    "\n",
    "# train_evaluate_model_from_config(configs.doc_retrieval.ru_odqa_infer_wiki_rubert, download=True)\n",
    "# train_evaluate_model_from_config(configs.squad.multi_squad_noans, download=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7A014tAAMBg_",
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "7A014tAAMBg_",
    "outputId": "4218e557-5254-4141-da5b-cb20404c2378"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-05-26 10:36:05.939 INFO in 'deeppavlov.models.vectorizers.hashing_tfidf_vectorizer'['hashing_tfidf_vectorizer'] at line 264: Loading tfidf matrix from /root/.deeppavlov/models/odqa/ruwiki_tfidf_matrix.npz\n"
     ]
    }
   ],
   "source": [
    "# Building\n",
    "odqa = build_model(configs.odqa.ru_odqa_infer_wiki_rubert, download=true)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1Rk1t5yjMHJI",
   "metadata": {
    "id": "1Rk1t5yjMHJI"
   },
   "outputs": [],
   "source": [
    "# Inference\n",
    "result = odqa(['Столица России?'])\n",
    "print(result)"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "name": "deeppavlov_answers.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
